name: "Build and publish"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate-matrix:
    name: "Generate matrix"
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set-matrix.outputs.packages }}

    steps:
      - name: Get source code
        uses: actions/checkout@v2

      # Don't know if I should use "origin/$GITHUB_BASE_REF" or ${{ github.event.pull_request.base.sha }}, same?
      - name: Check changed packages and generate matrix
        id: set-matrix
        run: |
          if [ $GITHUB_BASE_REF ]; then
            echo Pull
             export PREVIOUS_SHA="origin/$GITHUB_BASE_REF"
            # export PREVIOUS_SHA="${{ github.event.pull_request.base.sha }}"
          else
            echo Push
            export PREVIOUS_SHA="${{ github.event.before }}"
          fi
          export CURRENT_SHA="$GITHUB_SHA"

          echo PREVIOUS_SHA: $PREVIOUS_SHA
          echo CURRENT_SHA: $CURRENT_SHA
          echo GITHUB_SHA: $GITHUB_SHA

          JSON_PACKAGES=$( python generate_matrix.py )
          echo $JSON_PACKAGES
          echo "::set-output name=packages::$( echo $JSON_PACKAGES )"

  build:
    needs: generate-matrix

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        compiler: [msvc]
        package: ${{fromJson(needs.generate-matrix.outputs.packages)}}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Print
        run: echo ${{ matrix.package }}
